export default class IndexGenerator {
    /**
     * Will scan a source folder recursively and generate an index file in it that exports all files in the folder.
     * @param sourceFolder The root folder where the index file will be generated.
     * @param fileExtension The extension of the index file that is written.
     */
    static run(sourceFolder: string, fileExtension: 'mts'|'ts' = 'mts', alsoOutputJs: boolean = false) {
        const fileNames = this.findFiles(sourceFolder)
        const warning = '/*\n *\tOBS: Do not edit, this file was generated by the IndexGenerator.\n */'
        const encoder = new TextEncoder()
        const pattern = /(m?)ts$/i
        const replacement = '$1js'

        const outputFile = `${sourceFolder}/index.${fileExtension}`
        const rows = fileNames.map(row => `export * from './${row}'`)
        rows.unshift(warning)
        Deno.writeFileSync(outputFile, encoder.encode(rows.join("\n")))
        console.log(`Generated "${outputFile}" with ${rows.length} export(s).`)

        if(!alsoOutputJs) return

        const fileExtensionJs = fileExtension.replace(pattern, replacement)
        const outputFileJs = `${sourceFolder}/index.${fileExtensionJs}`
        const rowsJs = fileNames.map((row)=>{
            const rowJs = row.replace(pattern, replacement)
            return `export * from './${rowJs}'`
        })
        rowsJs.unshift(warning)
        Deno.writeFileSync(outputFileJs, encoder.encode(rowsJs.join("\n")))
        console.log(`Generated "${outputFileJs}" with ${rowsJs.length} export(s).`)
    }

    /**
     * Scan for files to generate exports for, will recursively traverse subfolders, skips index in the root.
     * @param path The folder to scan
     * @param subFolder Eventual subfolder we are traversing
     * @private
     */
    private static findFiles(path: string, subFolder: string = ''): string[] {
        if(subFolder.length > 0 && !subFolder.endsWith('/')) subFolder = `${subFolder}/`
        const files = Deno.readDirSync(path)
        const rows: string[] = []
        for(const dirEntry of files) {
            const fileName = dirEntry.name
            const filePath = `${path}/${fileName}`
            const lstat = Deno.lstatSync(filePath)
            if(lstat.isDirectory) {
                rows.push(...this.findFiles(filePath, `${subFolder}${fileName}`))
            } else {
                if(fileName.startsWith('index.')) continue
                if(!fileName.endsWith('.mts') && !fileName.endsWith('.ts')) continue
                rows.push(`${subFolder}${fileName}`)
            }
        }
        return rows
    }
}